spring:
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
    schema:
      inspection:
        enabled: true

logging:
  structured:
    format:
      console: logstash
    ecs:
      service:
        name: graphql-service
        version: 0.0.1
        environment: development
